# Generated by Django 5.0.2 on 2024-02-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Guidance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("level", models.CharField(max_length=10)),
                ("service_type", models.CharField(max_length=50)),
                ("department", models.CharField(max_length=150)),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
