# Generated by Django 5.0.4 on 2024-05-13 15:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("level", models.CharField(max_length=10)),
                ("service_type", models.CharField(max_length=50)),
                ("department", models.CharField(max_length=150)),
                ("reason", models.TextField()),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACCEPTED", "Accepted"), ("DRAFT", "Draft")],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("context", models.CharField(max_length=250)),
                ("time_stamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("READ", "Read")],
                        default="ACTIVE",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "ordering": ("-time_stamp",),
            },
        ),
    ]
