# Generated by Django 5.0.2 on 2024-02-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guidance",
            name="created_at",
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
