# Generated by Django 5.0.2 on 2024-02-20 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_guidance_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="guidance",
            old_name="created_at",
            new_name="date",
        ),
    ]
