# Generated by Django 5.0.2 on 2024-02-20 11:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_created_at_guidance_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guidance",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
    ]
