# Generated by Django 5.0.2 on 2024-02-20 11:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_guidance_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guidance",
            name="date",
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
