# Generated by Django 5.0.2 on 2024-02-20 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_guidance_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="guidance",
            old_name="date",
            new_name="date_booked",
        ),
    ]
